[project]
name = "predict-heart-disease"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kaggle>=2.0.0",
    "pytabkit[models]>=1.7.3",
    "tabpfn>=6.3.2",
]
